# env_file: .env

services:

  churnee:
    build:
      context: .
      dockerfile: Dockerfile 

    image: churnee:latest

    volumes:
      - ../models:/models
    
    environment:
      - MODEL_NAME=logisticreg_2025-06-12_14-06.joblib

    ports:
      - "4141:4141"

volumes:
  models: 
